name: Build Android Source
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # 1. Configura o Go
    - name: Configurar Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    # 2. Compila a ferramenta Fyne-Cross a partir do código fonte
    # Assim não dependemos de links quebrados ou versões confusas
    - name: Compilar Fyne-Cross do Zero
      run: |
        git clone https://github.com/fyne-io/fyne-cross.git
        cd fyne-cross
        go build -o fyne-cross ./cmd/fyne-cross
        sudo mv fyne-cross /usr/local/bin/
        cd ..

    # 3. Roda o Build do seu App
    # A primeira vez vai demorar uns 2-3 min baixando a imagem Docker interna
    - name: Compilar APK
      run: |
        fyne-cross android -appID com.rcappelatti.scanner -name "ScannerApp" -release=false

    # 4. Upload do resultado
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-android
        path: fyne-cross/bin/android/*.apk
