name: Build Android
on: [push]

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Compilar APK
      # Mudamos de @v2 para @master para garantir que ele pegue a versão mais recente
      uses: fyne-io/fyne-cross-action@master
      with:
        target: android
        # Removi o nome com espaços por enquanto para testar, deixei só o ID
        args: -appID com.rcappelatti.scanner

    - name: Upload do APK
      uses: actions/upload-artifact@v4
      with:
        name: app-android-debug
        path: fyne-cross/bin/android/*.apk
