name: Build Android Manual
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configurar Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Instalar Fyne-Cross
      run: go install github.com/fyne-io/fyne-cross/v3/cmd/fyne-cross@latest

    - name: Compilar APK
      # ADICIONADO: a flag -icon "Icon.png"
      # Certifique-se de que o arquivo Icon.png existe na raiz do projeto
      run: |
        fyne-cross android -appID com.rcappelatti.scanner -name "AcessaERP" -icon "Icon.png" -release=false

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-android
        path: fyne-cross/bin/android/*.apk
