name: Build Android Final
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configurar Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Instalar Fyne-Cross
      run: |
        git clone https://github.com/fyne-io/fyne-cross.git
        cd fyne-cross
        go install ./...
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Compilar APK
      run: |
        fyne-cross android -app-id com.rcappelatti.scanner -name "ScannerApp"

    # CORREÇÃO FINAL: Mudamos de /bin/ para /dist/
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-android
        path: fyne-cross/dist/android/*.apk
